name: Announce New Release

on:
  release:
    types: [published]

jobs:
  post:
    name: Send Announcement
    runs-on: ubuntu-latest
    steps:
      - name: Announce
        shell: bash
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d '{"content": "# Rosé Patcher ${{ github.event.release.tag_name }}\n-# A new version has been released!\n${{ github.event.release.body }}\n\n${{ github.event.release.html_url }}\n||<@${{ secrets.ROLE_ID }}>||", "username": "Rosé Patcher Updates", "avatar_url": "https://github.com/Project-Rose.png"}' \
            ${{ secrets.WEBHOOK_URL }}
          